MODULE: "Work Center MY"

# ─── File locations (relative to project root) ──────────────────────────────
TEMPLATE_PATH:        "Module/Work_Center/MC1_MNT-PM-M005_PM Work Center_MY_Preload_V2.xlsx" 
DATA_STANDARD_PATH:   "Metadata/DataStandard/DataStandardList.xlsx"
DATA_STANDARD_SHEET:  "Work Center"                          
MAPPING_PATH:         "Metadata/Mapping/KDS_ALL_MAPPING.xlsx"
OUTPUT_PATH:          "Output"
OUTPUT_FILE_NAME:     "MC1_MNT-PM-M005_PM Work Center_MY_Preload_V2 Data Cleansing.xlsx"                      

# ─── Ignore configuration ────────────────────────────────────────────────────
CONFIG_IGNORE_FIELD_SHEET: "Config_Ignore_Field"

IGNORE_COLUMN_SUFFIXES:
  - "_SRC"
  - "_DESC"
  - "SOURCE"
  - "REMARK"
  - "REMARKS"
  - "_DESCRIPTION"

# ─── Jobs (one per worksheet) ────────────────────────────────────────────────
JOBS:
  - NAME:          "1. Work Center Header"                 
    SHEET_KEYWORD: "PMWORKCENTER_CRHD_T_RPT_TH"             
    DS_TABLE:
      - "CRHD" 

    VALIDATIONS:
      - mandatory
      - length

    PRIMARY_KEYS:                  
      - ["OBJTY_TGT", "OBJID_TGT", "WERKS_TGT", "ARBPL_TGT"]

    FIXED_VALUE_FIELDS:
      # Only include active plants listed in the 'RR_TH_Active Plants' tab 
      #(refer to the PM Work Center Data Standard)
      - column: "WERKS_TGT"
        allowed_values:
          - “1201"
          - "1202"
          - "1602"
          - "1603"
          - "1604"
          - "1605"
          - "2101"
          - "2301"
          - "2801"
          - "4101"
          - "5101"
          - "5301"
          - "5302"
          - "5303"
          - "8401"
          - "MY01"
          - "MY02"
          - "MY05"
          - "MY06"
          - "MY07"
          - "2901"
          - "1401"

      # MY - Person Responsible for the Work Cente - Default ""
      - column: "VERAN_TGT"
        allowed_values:
          - ""
      
      # Control Key (STEUS) Default: PM01
      - column: "STEUS_TGT"
        allowed_values:
          - “PM01"

    PROHIBITED_NEWLINE_FIELDS:     [] 

    NON_BLANK_OPTIONAL_FIELDS:
      # Check Nonbalnk for Work Center column
      - "ARBPL_TGT"

    NON_BLANK_OPTIONAL_ANY_FIELDS: []
    SAME_SHEET_REFERENCES:         []
    CROSS_SHEET_REFERENCES:        []

    KDS_REFERENCES:
      # Plant
      - kds_sheet: "MY_T001W"
        kds_columns:
          - "WERKS_TGT"
        source_columns:
          - "WERKS_TGT"
        check_mapping:
          kds_src_columns:         
            - "WERKS_SRC"
          template_src_columns:      
            - "WERKS_SRC"

      # Work Center Category
      - kds_sheet: "MY_TC30"
        kds_columns:
          - "VERWE_TGT"
        source_columns:
          - "VERWE_TGT"
        check_mapping:
          kds_src_columns:         
            - "VERWE_SRC"
          template_src_columns:      
            - "VERWE_SRC"

      # Formula for set up time
      - kds_sheet: "MY_TC23"
        kds_columns:
          - "PLANV_TGT"
        source_columns:
          - "PLANV_TGT"
        check_mapping:
          kds_src_columns:         
            - "PLANV_SRC"
          template_src_columns:      
            - "PLANV_SRC"
      
      # Standard Value Key
      - kds_sheet: "MY_TC21"
        kds_columns:
          - "VGWTS_TGT"
        source_columns:
          - "VGWTS_TGT"
        check_mapping:
          kds_src_columns:         
            - "VGWTS_SRC"
          template_src_columns:      
            - "VGWTS_SRC"

       # Formula for setup time
      - kds_sheet: "MY_TC25"
        kds_columns:
          - "FORT1_TGT"
        source_columns:
          - "FORT1_TGT"
        check_mapping:
          kds_src_columns:         
            - "FORT1_SRC"
          template_src_columns:      
            - "FORT1_SRC"
      
      # Formula for the duration of processing time
      - kds_sheet: "MY_TC25"
        kds_columns:
          - "FORT1_TGT"
        source_columns:
          - "FORT2_TGT"
        check_mapping:
          kds_src_columns:         
            - "FORT1_SRC"
          template_src_columns:      
            - "FORT2_SRC"

      # Formula for teardown time
      - kds_sheet: "MY_TC25"
        kds_columns:
          - "FORT1_TGT"
        source_columns:
          - "FORT3_TGT"
        check_mapping:
          kds_src_columns:         
            - "FORT1_SRC"
          template_src_columns:      
            - "FORT3_SRC"
      # Formula for the duration of other types of int. processing
      - kds_sheet: "MY_TC25"
        kds_columns:
          - "FORT1_TGT"
        source_columns:
          - "FORTN_TGT"
        check_mapping:
          kds_src_columns:         
            - "FORT1_SRC"
          template_src_columns:      
            - "FORTN_SRC"

    
    KDS_PROHIBITED_REFERENCES:
      # Exclude work centers listed in the 'RR_TH_Deleted WC' tab (refer to the PM Work Center Data Standard), 
      # using the Plant and Work Center combination as the reference key
      - kds_sheet: "MY_WERK_ARBPL_EXC"
        kds_columns:
          - "WERKS_TGT"
          - "ARBPL_TGT"
        source_columns:
          - "WERKS_TGT"
          - "ARBPL_TGT"

    CUSTOM_VALIDATIONS:
      # Check BEGDA date format YYYYMMDD
      - check_ad_date:
        - BEGDA_TGT  
  



  
  - NAME:          "2. Text for the Work Center or Production Resource/Tool"                 
    SHEET_KEYWORD: "PMWORKCENTER_CRTX_T_RPT_TH"             
    DS_TABLE:
      - "CRTX"

    VALIDATIONS:
      - mandatory
      - length

    PRIMARY_KEYS:                  
      - ["WERKS", "ARBPL", "SPRAS_TGT"]

    FIXED_VALUE_FIELDS:     [] 

    PROHIBITED_NEWLINE_FIELDS:
      # Check no leading newline in text field
      - "KTEXT_TGT"

    NON_BLANK_OPTIONAL_FIELDS:     [] 
    NON_BLANK_OPTIONAL_ANY_FIELDS: []
    SAME_SHEET_REFERENCES:         []

    CROSS_SHEET_REFERENCES:
      # Check Parent-Child in Working Center Header Sheet (Plant + Work Center)
      - source_columns:       ["WERKS", "ARBPL"]
        target_sheet_keyword: "PMWORKCENTER_CRHD_T_RPT_TH"
        target_columns:       ["WERKS_TGT", "ARBPL_TGT"]

    KDS_REFERENCES:     [] 
    KDS_PROHIBITED_REFERENCES:     [] 
    CUSTOM_VALIDATIONS:     [] 





  
  - NAME:          "3. Assignment of Work Center to Cost Center"                 
    SHEET_KEYWORD: "PMWORKCENTER_CRCO_T_RPT_TH"             
    DS_TABLE:
      - "CRCO"

    VALIDATIONS:
      - mandatory
      - length

    PRIMARY_KEYS:                  
      - ["WERKS", "ARBPL", "LASET_TGT", "ENDDA_TGT", "LANUM_TGT"]

    FIXED_VALUE_FIELDS:     [] 
    PROHIBITED_NEWLINE_FIELDS:     [] 
    NON_BLANK_OPTIONAL_FIELDS:     [] 
    NON_BLANK_OPTIONAL_ANY_FIELDS: []
    SAME_SHEET_REFERENCES:         []

    CROSS_SHEET_REFERENCES: 
      # Check Parent-Child in Working Center Header Sheet (Plant + Work Center)
      - source_columns:       ["WERKS", "ARBPL"]
        target_sheet_keyword: "PMWORKCENTER_CRHD_T_RPT_TH"
        target_columns:       ["WERKS_TGT", "ARBPL_TGT"]
        
    KDS_REFERENCES:
      # Formula key for costing
      - kds_sheet: "MY_TC25"
        kds_columns:
          - "FORT1_TGT"
        source_columns:
          - "FORML_TGT"
        check_mapping:
          kds_src_columns:         
            - "FORT1_SRC"
          template_src_columns:      
            - "FORML_SRC"

      # Cost Center
      - kds_sheet: "MY_KOSTL"
        kds_columns:
          - "KOSTL_TGT"
        source_columns:
          - "KOSTL_TGT"
        check_mapping:
          kds_src_columns:         
            - "KOSTL_SRC"
          template_src_columns:      
            - "KOSTL_SRC"
      
      # MY - Activity Type
      - kds_sheet: "MY_KOSTL"
        kds_columns:
          - "LSTAR_TGT"
        source_columns:
          - "LSTAR_TGT"
        check_mapping:
          kds_src_columns:         
            - "LSTAR_SRC"
          template_src_columns:      
            - "LSTAR_SRC"
    

    KDS_PROHIBITED_REFERENCES:     [] 

    # START_WITH_FIELDS:
    #   # For Plant 1001 (Arti Plant) cost center have to start with "P"
    #   - column: "KOSTL_TGT"
    #     prefix:
    #       - "P"
    #     condition:
    #       column: "WERKS"
    #       values: ["1001"]

    CUSTOM_VALIDATIONS:
      # Check BEGDA ENDDA format YYYYMMDD
      - check_ad_date:
          - "BEGDA_TGT"     
          - "ENDDA_TGT"
      # Check valid start / end date
      - check_between_time:
        - start_date: "BEGDA_TGT"
          end_date:   "ENDDA_TGT"





  
  - NAME:          "4. Work Center Capacity Allocation"                 
    SHEET_KEYWORD: "PMWORKCENTER_CRCA_T_RPT_TH"             
    DS_TABLE:
      - "CRCA"

    VALIDATIONS:
      - mandatory
      - length

    PRIMARY_KEYS:                  
      - ["WERKS", "ARBPL"] 

    FIXED_VALUE_FIELDS:     [] 
    PROHIBITED_NEWLINE_FIELDS:     [] 
    NON_BLANK_OPTIONAL_FIELDS:     [] 
    NON_BLANK_OPTIONAL_ANY_FIELDS: []
    SAME_SHEET_REFERENCES:         []

    CROSS_SHEET_REFERENCES: 
      # Check Parent-Child in Working Center Header Sheet (Plant + Work Center)
      - source_columns:       ["WERKS", "ARBPL"]
        target_sheet_keyword: "PMWORKCENTER_CRHD_T_RPT_TH"
        target_columns:       ["WERKS_TGT", "ARBPL_TGT"]

    KDS_REFERENCES:
      # Formula for Setup Capacity Requirements
      - kds_sheet: "MY_TC25"
        kds_columns:
          - "FORT1_TGT"
        source_columns:
          - "FORK1_TGT"
        check_mapping:
          kds_src_columns:         
            - "FORT1_SRC"
          template_src_columns:      
            - "FORK1_SRC"
      
      # Formula for Processing Capacity Requirements
      - kds_sheet: "MY_TC25"
        kds_columns:
          - "FORT1_TGT"
        source_columns:
          - "FORK2_TGT"
        check_mapping:
          kds_src_columns:         
            - "FORT1_SRC"
          template_src_columns:      
            - "FORK2_SRC"

      # Formula for Teardown Capacity Requirements
      - kds_sheet: "MY_TC25"
        kds_columns:
          - "FORT1_TGT"
        source_columns:
          - "FORK3_TGT"
        check_mapping:
          kds_src_columns:         
            - "FORT1_SRC"
          template_src_columns:      
            - "FORK3_SRC"

      # Formula for Other Capacity Requirements
      - kds_sheet: "MY_TC25"
        kds_columns:
          - "FORT1_TGT"
        source_columns:
          - "FORKN_TGT"
        check_mapping:
          kds_src_columns:         
            - "FORT1_SRC"
          template_src_columns:      
            - "FORKN_SRC"

    KDS_PROHIBITED_REFERENCES:     [] 
    CUSTOM_VALIDATIONS:     [] 
  





  - NAME:          "5. Capacity Header Segment"                 
    SHEET_KEYWORD: "PMWORKCENTER_KAKO_T_RPT_TH"             
    DS_TABLE:
      - "KAKO"

    VALIDATIONS:
      - mandatory
      - length

    PRIMARY_KEYS:                  
      - ["WERKS", "ARBPL"] 

    FIXED_VALUE_FIELDS:
      # Capacity Responsible Planner Group - Default to PM 
      - column: "PLANR_TGT"
        allowed_values:
          - "PM"
      
      # MY - Default Capacity Utilization to “100” - dtype NUMC(3)
      - column: "NGRAD_TGT"
        allowed_values:
          - "100"

    PROHIBITED_NEWLINE_FIELDS:     [] 
    NON_BLANK_OPTIONAL_FIELDS:     [] 
    NON_BLANK_OPTIONAL_ANY_FIELDS: []
    SAME_SHEET_REFERENCES:         []

    CROSS_SHEET_REFERENCES: 
      # Check Parent-Child in Working Center Header Sheet (Plant + Work Center)
      - source_columns:       ["WERKS", "ARBPL"]
        target_sheet_keyword: "PMWORKCENTER_CRHD_T_RPT_TH"
        target_columns:       ["WERKS_TGT", "ARBPL_TGT"]

    KDS_REFERENCES:
      # Plant
      - kds_sheet: "MY_T001W"
        kds_columns:
          - "WERKS_TGT"
        source_columns:
          - "WERKS_TGT"
        check_mapping:
          kds_src_columns:         
            - "WERKS_SRC"
          template_src_columns:      
            - "WERKS_SRC"

    KDS_PROHIBITED_REFERENCES:     [] 
    CUSTOM_VALIDATIONS:     []





  
  - NAME:          "6. Capacity Description"                 
    SHEET_KEYWORD: "PMWORKCENTER_KAKT_T_RPT_TH"             
    DS_TABLE:
      - "KAKT"

    VALIDATIONS:
      - mandatory
      - length

    PRIMARY_KEYS:                  
      - ["WERKS", "ARBPL", "SPRAS_TGT"]

    FIXED_VALUE_FIELDS: []

    PROHIBITED_NEWLINE_FIELDS:
      # Check no \n in the column
      - "KTEXT_TGT"

    NON_BLANK_OPTIONAL_FIELDS:     [] 
    NON_BLANK_OPTIONAL_ANY_FIELDS: []
    SAME_SHEET_REFERENCES:         []

    CROSS_SHEET_REFERENCES: 
      # Check Parent-Child in Capacity Header Segment Sheet (Plant + Work Center)
      - source_columns:       ["WERKS", "ARBPL"]
        target_sheet_keyword: "PMWORKCENTER_KAKO_T_RPT_TH"
        target_columns:       ["WERKS", "ARBPL"]

    KDS_REFERENCES:     [] 
    KDS_PROHIBITED_REFERENCES:     [] 
    CUSTOM_VALIDATIONS:     [] 





  # - NAME:          "7. Shift Parameters for Available Capacity"                 
  #   SHEET_KEYWORD: ""             
  #   DS_TABLE:
  #     - "KAPA"

  #   VALIDATIONS:
  #     - mandatory
  #     - length

  #   PRIMARY_KEYS:                  
  #     - []

  #   FIXED_VALUE_FIELDS: []
  #   PROHIBITED_NEWLINE_FIELDS:
  #     - "KTEXT_TGT"
  #   NON_BLANK_OPTIONAL_FIELDS:     [] 
  #   NON_BLANK_OPTIONAL_ANY_FIELDS: []
  #   SAME_SHEET_REFERENCES:         []
  #   CROSS_SHEET_REFERENCES: 
  #   KDS_REFERENCES:     [] 
  #   KDS_PROHIBITED_REFERENCES:     [] 
  #   CUSTOM_VALIDATIONS:




  - NAME:          "8. Interval of Available Capacity"                 
    SHEET_KEYWORD: "PMWORKCENTER_KAZY_T_RPT_TH"             
    DS_TABLE:
      - "KAZY"

    VALIDATIONS:
      - mandatory
      - length

    PRIMARY_KEYS:                  
      - ["WERKS", "ARBPL", "VERSN_TGT", "DATUB_TGT"]

    FIXED_VALUE_FIELDS: []

    PROHIBITED_NEWLINE_FIELDS:
      # Check no \n in the column
      - "KTEXT_TGT"

    NON_BLANK_OPTIONAL_FIELDS:     [] 
    NON_BLANK_OPTIONAL_ANY_FIELDS: []
    SAME_SHEET_REFERENCES:         []

    CROSS_SHEET_REFERENCES: 
      # Check Parent-Child in Working Center Header Sheet (Plant + Work Center)
      - source_columns:       ["WERKS", "ARBPL"]
        target_sheet_keyword: "PMWORKCENTER_CRHD_T_RPT_TH"
        target_columns:       ["WERKS_TGT", "ARBPL_TGT"]

    KDS_REFERENCES:     [] 
    KDS_PROHIBITED_REFERENCES:     [] 

    CUSTOM_VALIDATIONS:
      # Check date format YYYYMMDD
      - check_ad_date:
          - "DATUB_TGT"
  

  - NAME:          "9. STXD SAPscript text file header, STXD SAPscript text file lines"                 
    SHEET_KEYWORD: "PMWORKCENTER_STXH_STXL_T_RPT_TH"             
    DS_TABLE:
      - "STXH"
      - "STXL"

    VALIDATIONS:
      - mandatory
      - length

    PRIMARY_KEYS: 
      - ["WERKS", "ARBPL", "TDID_TGT", "TDNAME_TGT", "TDSPRAS_TGT"]

    FIXED_VALUE_FIELDS: []
    PROHIBITED_NEWLINE_FIELDS:  []
    NON_BLANK_OPTIONAL_FIELDS:     [] 
    NON_BLANK_OPTIONAL_ANY_FIELDS: []
    SAME_SHEET_REFERENCES:         []

    CROSS_SHEET_REFERENCES: 
      # Check Parent-Child in Working Center Header Sheet (Plant + Work Center)
      - source_columns:       ["WERKS", "ARBPL"]
        target_sheet_keyword: "PMWORKCENTER_CRHD_T_RPT_TH"
        target_columns:       ["WERKS_TGT", "ARBPL_TGT"]

    KDS_REFERENCES:     [] 
    KDS_PROHIBITED_REFERENCES:     [] 
    CUSTOM_VALIDATIONS: []