WITH STAT_ALL AS (  
    SELECT *  
    FROM (  
        SELECT   
            EQUI.OBJNR		
            , EQUI.EQUNR  
            , JEST.STAT  
            , JEST.INACT  
            , JEST.CHGNR  
            , JCDS.UDATE  
            , JCDS.UTIME  
            , ROW_NUMBER() OVER (PARTITION BY JEST.OBJNR ORDER BY JCDS.UDATE DESC , JCDS.UTIME DESC, JEST.CHGNR DESC, JEST.STAT DESC) RN  
        FROM SRCSAPECC_TL..EQUI AS EQUI  
        LEFT JOIN SRCSAPECC_TL..JEST AS JEST  ON EQUI.OBJNR = JEST.OBJNR  
        LEFT JOIN SRCSAPECC_TL..JCDS AS JCDS   
            ON JCDS.OBJNR = EQUI.OBJNR AND JCDS.STAT = JEST.STAT AND JCDS.INACT = JEST.INACT AND JCDS.CHGNR = JEST.CHGNR  
        WHERE 1=1   
            AND JEST.STAT LIKE 'I%'  
            AND JEST.INACT <> 'X'  
    ) AS LATEST_STAT  
    WHERE RN = 1  
)  

SELECT 
    ST.*
    , S.MANDT
    , Z.ILOAN
    , L.TPLNR
    , S.zActive
    , '1' as ZActiveNew 
FROM EQ_EQUI_SAPECC_TL_EQUI_S S  
LEFT JOIN STAT_ALL ST 
    ON ST.EQUNR = S.EQUNR
LEFT JOIN SRCSAPECC_TL..EQUZ Z 
    ON DATBI='99991231' AND S.EQUNR = Z.EQUNR
LEFT JOIN SRCSAPECC_TL..ILOA L 
    ON Z.ILOAN = L.ILOAN
WHERE 1=1  
    AND ST.STAT NOT IN ('I0076', 'I0320', 'I0013') 
    AND L.TPLNR<>''