-- latest action for JEST

SELECT 
 IFLOT.OBJNR
 , IFLOT.TPLNR
 , JEST.STAT
 , JEST.INACT
 , JEST.CHGNR
 , TJ02T.TXT04
 , TJ02T.TXT30
 , JCDS.UDATE
 , JCDS.UTIME

FROM SRCSAPECC_MY..IFLOT AS IFLOT
JOIN SRCSAPECC_MY..JEST AS JEST
    ON IFLOT.OBJNR = JEST.OBJNR
JOIN SRCSAPECC_MY..TJ02T AS TJ02T
    ON JEST.STAT = TJ02T.ISTAT
JOIN SRCSAPECC_MY..JCDS AS JCDS
    ON JCDS.OBJNR = IFLOT.OBJNR AND JCDS.STAT = JEST.STAT
WHERE 1=1
    AND JEST.OBJNR = 'IF?0100000000000004806'
    AND TJ02T.SPRAS = 'E'

ORDER BY JCDS.UDATE DESC, JCDS.UTIME DESC
;



SELECT 
 IFLOT.OBJNR
 , IFLOT.TPLNR
 , JEST.STAT
 , JEST.INACT
 , JEST.CHGNR
 , JCDS.UDATE
 , JCDS.UTIME

FROM SRCSAPECC_TL..IFLOT AS IFLOT
JOIN SRCSAPECC_TL..JEST AS JEST
    ON IFLOT.OBJNR = JEST.OBJNR
JOIN SRCSAPECC_TL..JCDS AS JCDS
    ON JCDS.OBJNR = IFLOT.OBJNR AND JCDS.STAT = JEST.STAT
WHERE 1=1
    --  AND JEST.OBJNR = 'IF?0100000000000004806'
    AND IFLOT.TPLNR = 'ART-FB-11-423'
ORDER BY JCDS.UDATE DESC, JCDS.UTIME DESC
;



WITH STAT_ALL AS (
    SELECT *
    FROM (
        SELECT 
            IFLOT.OBJNR
            , IFLOT.TPLNR
            , JEST.STAT
            , JEST.INACT
            , JEST.CHGNR
            , JCDS.UDATE
            , JCDS.UTIME
            , ROW_NUMBER() OVER (PARTITION BY JEST.OBJNR ORDER BY JCDS.UDATE DESC , JCDS.UTIME DESC, JEST.CHGNR DESC) RN
        FROM SRCSAPECC_TL..IFLOT AS IFLOT
        JOIN SRCSAPECC_TL..JEST AS JEST 
            ON IFLOT.OBJNR = JEST.OBJNR
        JOIN SRCSAPECC_TL..JCDS AS JCDS 
            ON JCDS.OBJNR = IFLOT.OBJNR AND JCDS.STAT = JEST.STAT AND JCDS.INACT = JEST.INACT AND JCDS.CHGNR = JEST.CHGNR
        WHERE 1=1 
            JEST.STAT LIKE 'I%'
            -- AND JCDS.OBJNR='IF00000000000000000012'
    ) AS LATEST_STAT
    WHERE RN = 1
)
 
Select TOP(20) *
from STAT_ALL 
;

-- JEST.INACT -> บอกว่่า STATUS นี้ยัง Active ไหม
-- Logic -> เราจะเช็ค STATUS ล่างสุดของ OBJNR นั้นๆ ที่ไม่โดน Mark ว่า INAC มาเช็คว่า OBJNR นั้นๆมี Status เป็น 'I0076', 'I0013', 'I0320 ไหม ถ้ามีจะนับว่าเป็น deletion flag

WITH STAT_ALL AS (
    SELECT *
    FROM (
        SELECT 
            IFLOT.OBJNR
            , IFLOT.TPLNR
            , JEST.STAT
            , JEST.INACT
            , JEST.CHGNR
            , JCDS.UDATE
            , JCDS.UTIME
            , ROW_NUMBER() OVER (PARTITION BY JEST.OBJNR ORDER BY JCDS.UDATE DESC , JCDS.UTIME DESC, JEST.CHGNR DESC, JEST.STAT DESC) RN
        FROM SRCSAPECC_TL..IFLOT AS IFLOT
        LEFT JOIN SRCSAPECC_TL..JEST AS JEST 
            ON IFLOT.OBJNR = JEST.OBJNR
        LEFT JOIN SRCSAPECC_TL..JCDS AS JCDS 
            ON JCDS.OBJNR = IFLOT.OBJNR AND JCDS.STAT = JEST.STAT AND JCDS.INACT = JEST.INACT AND JCDS.CHGNR = JEST.CHGNR
        WHERE 1=1 
            AND JEST.STAT LIKE 'I%'
            AND JEST.INACT != 'X'
    ) AS LATEST_STAT
    WHERE RN = 1
)
 
SELECT *
FROM STAT_ALL
WHERE 1=1
    AND STAT NOT IN ('I0076', 'I0320', 'I0013')

