SELECT 
	COUNT(OBJNR) AS CNT_REC
	, COUNT(DISTINCT OBJNR) AS CNT_DIS_REC
FROM SRCSAPECC_TL..JEST AS JEST
WHERE 1=1
    AND ( JEST.STAT IN ('I0076', 'I0013')  OR JEST.INACT != '')
;

-- FLOC_DEL_FLAG
SELECT 
    -- DISTINCT TPLNR

	TOP(30)
	IFLOT.OBJNR
	, IFLOT.TPLNR
	, JEST.STAT
	, JEST.INACT

	-- , COUNT(IFLOT.OBJNR) AS CNT_REC
	-- , COUNT(DISTINCT IFLOT.OBJNR) AS CNT_DIS_REC

FROM SRCSAPECC_TL..IFLOT AS IFLOT
JOIN SRCSAPECC_TL..JEST AS JEST
	ON IFLOT.OBJNR = JEST.OBJNR
WHERE 1=1
    AND ( JEST.STAT IN ('I0076', 'I0013')  OR JEST.INACT != '')
;


WITH active_floc as (
    SELECT
        TOP(10)
        *
        , row_number() OVER(PARTITION BY OBJNR ORDER BY JEST.CHGNR DESC) as rn
    FROM SRCSAPECC_TL..JEST AS JEST
    ORDER BY JEST.OBJNR
)

;

