-- Checking Number of Extraction Record -- 330534
SELECT
    COUNT(IFLOT.OBJNR)
FROM SRCSAPECC_TL..IFLOT AS IFLOT
JOIN SRCSAPECC_TL..JEST AS JEST
    ON IFLOT.OBJNR = JEST.OBJNR
WHERE 1=1
    AND JEST.STAT NOT IN ('I0076', 'I0013')
    AND JEST.INACT = ''
;

